import docker
import os
import logging
from typing import Dict, Any, Optional
from docker.errors import APIError, ImageNotFound

logger = logging.getLogger(__name__)

class ContainerService:
    """
    Production-grade service to manage Docker containers dynamically.
    Uses the Docker SDK for Python to interact with the local/remote Docker daemon.
    """
    
    def __init__(self):
        try:
            self.client = docker.from_env()
            logger.info("Successfully connected to Docker Daemon")
        except Exception as e:
            logger.error(f"Failed to connect to Docker Daemon: {e}")
            self.client = None

    async def build_image(self, path: str, tag: str, build_args: Dict[str, str] = None) -> str:
        """
        Builds a Docker image from a directory.
        DevOps Logic: Multi-stage builds are handled via the Dockerfile generated by BuilderService.
        """
        if not self.client:
            raise Exception("Docker client not initialized")
            
        logger.info(f"Starting build for tag: {tag} at path: {path}")
        try:
            image, logs = self.client.images.build(
                path=path,
                tag=tag,
                buildargs=build_args,
                rm=True  # Remove intermediate containers
            )
            # Log the build process (this would be streamed to the frontend Logs page)
            for line in logs:
                if 'stream' in line:
                    logger.debug(line['stream'].strip())
            
            return image.id
        except Exception as e:
            logger.error(f"Build failed: {e}")
            raise e

    async def run_container(self, image_tag: str, name: str, env_vars: Dict[str, str], port: int) -> Dict[str, Any]:
        """
        Starts a container with dynamic port mapping and resource limits.
        DevOps Logic: Isolate containers using bridge networks and limit RAM/CPU.
        """
        if not self.client:
            raise Exception("Docker client not initialized")

        try:
            # Remove existing container if it exists (for redeployments)
            try:
                old_container = self.client.containers.get(name)
                old_container.stop()
                old_container.remove()
            except docker.errors.NotFound:
                pass

            container = self.client.containers.run(
                image_tag,
                name=name,
                detach=True,
                environment=env_vars,
                ports={f'80/tcp': port}, # Map internal 80 (default) to a dynamic host port
                mem_limit='512m',        # Resource limit: 512MB RAM
                nano_cpus=500000000,     # Resource limit: 0.5 CPU
                restart_policy={"Name": "always"}
            )
            
            return {
                "container_id": container.id,
                "status": container.status,
                "port": port
            }
        except APIError as e:
            logger.error(f"Failed to run container {name}: {e}")
            raise e

    async def get_container_stats(self, container_id: str) -> Dict[str, Any]:
        """
        Real-time monitoring: Fetches CPU and RAM usage directly from the Docker engine.
        This data is fed into Prometheus/Grafana.
        """
        try:
            container = self.client.containers.get(container_id)
            stats = container.stats(stream=False)
            
            # DevOps Calculation: CPU % and Memory usage
            cpu_delta = stats['cpu_stats']['cpu_usage']['total_usage'] - stats['precpu_stats']['cpu_usage']['total_usage']
            system_delta = stats['cpu_stats']['system_cpu_usage'] - stats['precpu_stats']['system_cpu_usage']
            cpu_percent = (cpu_delta / system_delta) * len(stats['cpu_stats']['cpu_usage']['percpu_usage']) * 100.0
            
            mem_usage = stats['memory_stats']['usage'] / (1024 * 1024) # MB
            
            return {
                "cpu_percent": round(cpu_percent, 2),
                "memory_mb": round(mem_usage, 2),
                "status": container.status
            }
        except Exception as e:
            logger.error(f"Failed to get stats for {container_id}: {e}")
            return {"error": str(e)}

# Initialize global service
container_manager = ContainerService()
